medical_keywords = [word.lower() for word in [ 
  
# Systemic Lupus Erythematosus (Lupus)
"Lupus",
"SLE",
"Systemic Lupus Erythematosus",
"Systemic-Lupus-Erythematosus",
"Lupus Erythematosus Disseminatus",
"Libman-Sacks Disease",
"Disease, Libman-Sacks",
"Libman Sacks Disease",

# HIV/AIDS
"Human Immunodeficiency Virus",
"Acquired Immunodeficiency Syndrome",
"Human-Immunodeficiency-Virus",
"Acquired-Immunodeficiency-Syndrome",
"HIV/AIDS",
"AIDS/HIV",
"AIDS-HIV",
"HIV-AIDS",
"HIV",
"AIDS",

"Immunodeficiency Virus, Human",
"Immunodeficiency Viruses, Human",
"Virus, Human Immunodeficiency2",
"Viruses, Human Immunodeficiency",
"Human Immunodeficiency Viruses",
"Human T Cell Lymphotropic Virus Type III",
"Human T-Cell Lymphotropic Virus Type III",
"Human T-Cell Leukemia Virus Type III",
"Human T Cell Leukemia Virus Type III",
"LAV-HTLV-III",
"Lymphadenopathy-Associated Virus",
"Lymphadenopathy Associated Virus",
"Lymphadenopathy-Associated Viruses",
"Virus, Lymphadenopathy-Associated",
"Viruses, Lymphadenopathy-Associated",
"Human T Lymphotropic Virus Type III", 
"Human T-Lymphotropic Virus Type III",
"AIDS Virus",
"AIDS Viruses",
"Virus, AIDS",
"Viruses, AIDS",
"Acquired Immune Deficiency Syndrome Virus",
"Acquired Immunodeficiency Syndrome Virus",
"HTLV-III",

# Prostate Cancer
"Prostate Neoplasms",
"Neoplasms, Prostate"
"Neoplasm, Prostate",
"Prostate Neoplasm",
"Neoplasms, Prostatic",
"Neoplasm, Prostatic",
"Prostatic Neoplasm",
"Prostate Cancer",
"Cancer, Prostate",
"Cancers, Prostate",
"Prostate Cancers",
"Cancer of the Prostate",
"Prostatic Cancer",
"Cancer, Prostatic",
"Cancers, Prostatic",
"Prostatic Cancers",
"Cancer of Prostate",

# COVID-19
"SARS-CoV-2 Virus",
"SARS CoV 2 Virus",
"SARS-CoV-2 Viruses",
"Virus, SARS-CoV-2",
"2019 Novel Coronavirus",
"2019 Novel Coronaviruses",
"Coronavirus, 2019 Novel",
"Novel Coronavirus, 2019",
"COVID-19 Virus",
"COVID 19 Virus",
"COVID-19 Viruses",
"Virus, COVID-19",
"Wuhan Coronavirus",
"Coronavirus, Wuhan",
"COVID19 Virus",
"COVID19 Viruses",
"Virus, COVID19",
"Viruses, COVID19",
"Coronavirus Disease 2019 Virus",
"Severe Acute Respiratory Syndrome Coronavirus 2",
"SARS Coronavirus 2",
"Coronavirus 2, SARS",
"2019-nCoV",
"Wuhan Seafood Market Pneumonia Virus",
"SARS-CoV-2",
"SARS CoV 2",
"COVID-19",
"COVID19",
"COVID 19",
"Coronavirus Disease 2019",
"Novel Coronavirus",
"Novel-Coronavirus",
"2019-nCoV",
"2019 nCoV",

## Takotsubo Cardiomyopathy
"Takotsubo Cardiomyopathy",
"Cardiomyopathy, Takotsubo",
"Tako-Tsubo Syndrome",
"Syndrome, Tako-Tsubo",
"Tako Tsubo Syndrome",
"Tako-Tsubo Syndromes",
"Left Ventricular Apical Ballooning Syndrome",
"Broken Heart Syndrome",
"Takotsubo Syndrome",
"Transient Apical Ballooning Syndrome",
"Apical Ballooning Syndrome",
"Tako-Tsubo Cardiomyopathy",
"Cardiomyopathy, Tako-Tsubo",
"Tako Tsubo Cardiomyopathy",
"Tako-Tsubo Cardiomyopathies",
"Stress Cardiomyopathy",
"Cardiomyopathy, Stress",

#Multiple Sclerosis 
  
"Multiple Sclerosis",
"Sclerosis, Multiple",
"Sclerosis, Disseminated",
"Disseminated Sclerosis",
"MS (Multiple Sclerosis)",
"Multiple Sclerosis, Acute Fulminating",

# Colon Cancer

"Colonic Neoplasm",
"Neoplasm, Colonic",
"Neoplasms, Colonic",
"Colon Neoplasms",
"Colon Neoplasm",
"Neoplasm, Colon",
"Neoplasms, Colon",
"Cancer of Colon",
"Colon Cancers",
"Colon Cancer",
"Cancer, Colon",
"Cancers, Colon",
"Cancer of the Colon",
"Colonic Cancer",
"Cancer, Colonic",
"Cancers, Colonic",
"Colonic Cancers",
"Colon Adenocarcinoma",
"Adenocarcinoma, Colon",
"Adenocarcinomas, Colon",
"Colon Adenocarcinomas",
  
#Tuberculoses
"Tuberculoses"
"Kochs Disease",
"Koch's Disease",
"Koch Disease",
"Mycobacterium tuberculosis Infection",
"Infection, Mycobacterium tuberculosis",
"Infections, Mycobacterium tuberculosis",
"Mycobacterium tuberculosis Infections",

#Bacterial Pneumonia
  
"Bacterial Pneumonia",
"Bacterial Pneumonias",
"Pneumonias, Bacterial",

#Endocarditis 
  
"Tricuspid Endocarditis",
"Endocarditides",
"Infective Endocarditis",
"Endocarditides, Infective",
"Endocarditis, Infective",
"Infective Endocarditides",

# Syphilis
  
"Syphilis",
"Great Pox",

# Type 2 Diabetes 

"Diabetes Mellitus, Noninsulin-Dependent",
"Diabetes Mellitus, Ketosis-Resistant",
"Diabetes Mellitus, Ketosis Resistant",
"Ketosis-Resistant Diabetes Mellitus",
"Diabetes Mellitus, Non Insulin Dependent",
"Diabetes Mellitus, Non-Insulin-Dependent",
"Non-Insulin-Dependent Diabetes Mellitus",
"Diabetes Mellitus, Stable",
"Stable Diabetes Mellitus",
"Diabetes Mellitus, Type II",
"NIDDM",
"Diabetes Mellitus, Noninsulin Dependent",
"Diabetes Mellitus, Maturity-Onset",
"Diabetes Mellitus, Maturity Onset",
"Maturity-Onset Diabetes Mellitus",
"Maturity Onset Diabetes Mellitus",
"MODY",
"Diabetes Mellitus, Slow-Onset",
"Diabetes Mellitus, Slow Onset",
"Slow-Onset Diabetes Mellitus",
"Type 2 Diabetes Mellitus",
"Noninsulin-Dependent Diabetes Mellitus",
"Noninsulin Dependent Diabetes Mellitus",
"Maturity-Onset Diabetes",
"Diabetes, Maturity-Onset",
"Maturity Onset Diabetes",
"Type 2 Diabetes",
"Diabetes, Type 2",
"Diabetes Mellitus, Adult-Onset",
"Adult-Onset Diabetes Mellitus",
"Diabetes Mellitus, Adult Onset",

# Multiple myloma

"Multiple Myelomas",
"Myelomas, Multiple",
"Myeloma, Multiple",
"Myeloma, Plasma-Cell",
"Myeloma, Plasma Cell",
"Myelomas, Plasma-Cell",
"Plasma-Cell Myeloma",
"Plasma-Cell Myelomas",
"Myelomatosis",
"Myelomatoses",
"Plasma Cell Myeloma",
"Cell Myeloma, Plasma",
"Cell Myelomas, Plasma",
"Myelomas, Plasma Cell",
"Plasma Cell Myelomas",
"Kahler Disease",
"Disease, Kahler",
"Myeloma-Multiple",
"Myeloma Multiple",
"Myeloma-Multiples",

# Essential Hypertension

"Primary Hypertension",
"Hypertension, Primary",
"Hypertensions, Primary",
"Primary Hypertensions",
"Hypertension, Essential",
  
#Sarcoidoses
"Sarcoidoses",
"Boeck's Sarcoid",
"Boeck Sarcoid",
"Boecks Sarcoid",
"Sarcoid, Boeck's",
"Schaumann Disease",
"Disease, Schaumann",
"Schaumann Syndrome",
"Syndrome, Schaumann",
"Besnier-Boeck-Schaumann Syndrome",
"Besnier Boeck Schaumann Syndrome",
"Syndrome, Besnier-Boeck-Schaumann",
"Boeck Disease",
"Boeck's Disease",
"Boecks Disease",
"Besnier-Boeck Disease",
"Besnier Boeck Disease",
"Schaumann's Syndrome",
"Schaumann's Syndromes",
"Syndrome, Schaumann's"

#Rheumatoid Arthritis

"Rheumatoid Arthritis",

#Hepatitis B 

"Hepatitis B 

  
]]
